// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YZWX9KUmgoqX6AiMEp49KetA-W85CIk',
    appId: '1:995535828722:web:4af83b18c52edbb40e026b',
    messagingSenderId: '995535828722',
    projectId: 'velvetleashapp-4b8e1',
    authDomain: 'velvetleashapp-4b8e1.firebaseapp.com',
    storageBucket: 'velvetleashapp-4b8e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvT_zij83VG7yzbXh7UIhBPJwTpuqZk4',
    appId: '1:995535828722:android:4745e6ec57cd7bb50e026b',
    messagingSenderId: '995535828722',
    projectId: 'velvetleashapp-4b8e1',
    storageBucket: 'velvetleashapp-4b8e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YZWX9KUmgoqX6AiMEp49KetA-W85CIk',
    appId: '1:995535828722:web:553e7f56ceed07730e026b',
    messagingSenderId: '995535828722',
    projectId: 'velvetleashapp-4b8e1',
    authDomain: 'velvetleashapp-4b8e1.firebaseapp.com',
    storageBucket: 'velvetleashapp-4b8e1.firebasestorage.app',
  );
}
